### PR TITLE
Start momentum from pagePoint

### PR DESCRIPTION
**Pull request by T-Wizard**
It differs from point on svg elements

### CODE REVIEW

**Comment by stoffeastrom** [comment]
@peol @edvard-falkskar

**Comment by stoffeastrom** [comment]
@T-Wizard can you update the PR with updated `dist` folder?

**Comment by edvard-falkskar** [comment]
LGTM 👍

**Comment by edvard-falkskar** [comment]
@T-Wizard You should bump the version to :)

**Review by edvard-falkskar — APPROVED** [review]

**Pull request merged**
