### PR TITLE
Momentum

### PR DESCRIPTION
**Pull request by nilzona**
touche momentum

### CODE REVIEW

**Comment by stoffeastrom** [comment]
Looks like you have to get latest and put the code in the correct files! :)

**Comment by nilzona** [comment]
I don't get it .. I forked today

**Comment by stoffeastrom** [comment]
The swipe gesture file that should be changed is located under lib/core/gestures/swipe.js. Looks like the file in your PR is prefixed with touche-swipe.js ? 

So basically the source that should be changed is located under [lib/core/_.js], [lib/gesture/_.js].

Maybe you forked the old master repo? The one you forked looks like an old version! Make sure the one you fork is gh-pages

**Comment by nilzona** [comment]
yes, for some reason I had an old fork ... forget this request then, I'll make a new one

**Pull request closed without merging**
